scene:
  scene_path: "/local_datasets/mipnerf360/bicycle"
  test_cameras: False
  colmap_images: "images"
  colmap_eval_hold: 8
  downscale_ratio: 1
  white_background: False
  device: "cuda:0"
  
pipeline:
  convert_shs_python: False
  compute_cov3d_python: False
  debug: False
  seed: 0

model:
  sh_degree: 3
  model_dir: "/data/shjin1019/semantic-gaussians/output/bicycle"
  load_iteration: -1
  device: "cuda:0"
  random_init: False

train:
  exp_name: "bicycle_mipnerf360"
  iterations: 30000
  num_workers: 8
  test_iterations: [100, 7000, 30000]
  save_iterations: [7000, 30000]
  checkpoint_iterations: []
  cut_edge: False

  position_lr_init: 0.00016
  position_lr_final: 0.0000016
  position_lr_delay_mult: 0.01
  position_lr_max_steps: 10000
  feature_lr: 0.0025
  opacity_lr: 0.05
  scaling_lr: 0.005
  rotation_lr: 0.001
  percent_dense: 0.01
  lambda_dssim: 0.2
  densification_interval: 100
  opacity_reset_interval: 3000
  densify_from_iter: 500
  densify_until_iter: 15000
  densify_grad_threshold: 0.0002
  random_background: False